port_configs:
  - type: USP
  - type: DSP
  - type: DSP
virtual_switch_configs:
  - upstream_port_index: 0
    vppb_counts: 2
    initial_bounds: [1,2]
hdm_decoder_capabilities:
  decoder_count: 2
  target_count: 2
  bi_capable: False
devices:
  single_logical_devices:
    - port_index: 1
      memory_size: 256M
      serial_number: 4E9FF1671694A385
  generic_fabric_devices:
    - port_index: 2
      serial_number: 2200B90031B3ABD8
