port_configs:
  - type: USP
  - type: DSP
  - type: DSP
  - type: DSP
  - type: DSP
  - type: USP
  - type: DSP
  - type: DSP
  - type: DSP
  - type: DSP
virtual_switch_configs:
  - upstream_port_index: 0
    vppb_counts: 4
    initial_bounds: [1,2,3,4]
  - upstream_port_index: 5
    vppb_counts: 4
    initial_bounds: [6,7,8,9]
devices:
  - port_index: 1
    memory_size: 256M
    serial_number: 4E9FF1671694A385
  - port_index: 2
    memory_size: 256M
    serial_number: 2200B90031B3ABD8
  - port_index: 3
    memory_size: 256M
    serial_number: 3B0357B80F50A534
  - port_index: 4
    memory_size: 256M
    serial_number: CB6575D3D9A4FC7A
  - port_index: 6
    memory_size: 256M
    serial_number: 3FB95963144632BF
  - port_index: 7
    memory_size: 256M
    serial_number: BDFF0BABB1E6EB94
  - port_index: 8
    memory_size: 256M
    serial_number: 8A440DABC4DBEAFB
  - port_index: 9
    memory_size: 256M
    serial_number: CBC9436B5B325BEC